### ISSUE TITLE
Gender is not displayed or demanded in the register form

### ISSUE THREAD

**Issue by fxleblanc** [MaisonLogicielLibre/Website#863]
What should we do with the gender?

**Comment by RignonNoel** [comment]
We just want stats about users.

**Comment by RaphaelStArnaud** [comment]
Try not to bloat the register form with non-essential information

**Comment by fxleblanc** [comment]
The user can edit his gender after registration but it's not even displayed on his profile page. My question is then, should we display the gender in the profile?

**Comment by RignonNoel** [comment]
This field is not displayed because is a personnal field. We dont need to know the gender of the user to work with.
And i think it's maybe illégal to show the gender on a site of recruitment .
Le 27 janv. 2016 9:05 AM, Félix Leblanc <notifications@github.com> a écrit :The user can edit his gender after registration but it's not even displayed on his profile page. My question is then, should we display the gender in the profile?

**Comment by fxleblanc** [comment]
Thanks for clarification. Closing
